name: Build and Push Base Docker Image

on:
  push:
    paths:
      - conanfile.txt
      - conanProfiles/conanProfileRelease_Linux
      - Dockerfile.base

jobs:
  build_and_push_gcc14_conan:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define tags
        id: vars
        run: |
          IMAGE=ghcr.io/rouvald/gcc14_conan
          echo "sha_tag=${IMAGE}:sha-${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "latest_tag=${IMAGE}:latest" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -f Dockerfile.base -t ${{ steps.vars.outputs.sha_tag }} .
          docker tag ${{ steps.vars.outputs.sha_tag }} ${{ steps.vars.outputs.latest_tag }}

      - name: Push image
        run: |
          docker push ${{ steps.vars.outputs.sha_tag }}
          docker push ${{ steps.vars.outputs.latest_tag }}
